# Generated by Django 5.1.15 on 2026-01-18 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameState",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "board_size",
                    models.IntegerField(
                        choices=[(9, 9), (13, 13), (19, 19)], default=19
                    ),
                ),
                ("komi", models.FloatField(default=6.5)),
                (
                    "user_color",
                    models.CharField(
                        choices=[("B", "Black"), ("W", "White")],
                        default="B",
                        max_length=1,
                    ),
                ),
                ("game_over", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("persona", models.CharField(default="arrogant", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Bot")], max_length=20
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="game.gamestate",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[("B", "Black"), ("W", "White")], max_length=1
                    ),
                ),
                ("coordinate", models.CharField(max_length=5)),
                ("move_number", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="game.gamestate",
                    ),
                ),
            ],
        ),
    ]
