# Generated by Django 5.1.15 on 2026-01-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamestate",
            name="handicap",
            field=models.IntegerField(default=0),
        ),
    ]
